.TH IPE5TOXML "1" "December 2011" "Ipe" "User Commands"

.SH NAME
ipe5toxml \- Convert Ipe 5 file to Ipe 6 format

.SH SYNOPSIS
.B ipe5toxml
\fIfile.ipe file.xml\fR

.SH DESCRIPTION
\fBipe5toxml\fR converts an Ipe version 5 format file to one understood by Ipe version 6.
Use \fBipe6upgrade\fR to convert the output XML file to one understood by Ipe version 7.

.SH AUTHOR
Otfried Cheong

.SH "SEE ALSO"
\fBipe6upgrade\fR(1)
